4 feature 4 tomato timer
CSC207-2022F-UofT/course-project-kronos pull request #22
Opened 2022-11-21 19:57 UTC by AngelEyesMagicMaker

Description: This pull request implements the Timer entities, use cases, UI and controller files for the Timer. The code finished most of the functions that we want on the Timer, but it still needs to improve and fix the problems in the UI and add files to use cases and controller packages.

Designs:

I created a main file called TimerScreen for the UI package.

Design Pattern:

Façade (for use cases)

Unit tests: About 0%. Since the files and the type of input is still changing, the test will be covered after the timer functions are in good use.

Exception Handling: Incomplete.

JavaDocs Documentation: Documentations are added to some functions.

SOLID Principles: Followed Single Responsibility Principle, all files follow the Open/Close principle and Interface Segregation.

Clean Architecture: The structure follows Clean Architecture, but the UI package still needs fixing.

2022-11-21 20:28 UTC, EmilyDo commented on src/main/java/controllers/TimerController.java
> +        TimerOutputBoundary TimerOutput = new TimerOutputBoundary(w, r);
just as a convention object names start with lower case (timerOutput)

2022-11-21 20:33 UTC, EmilyDo commented on src/main/java/use_cases/TimerCycle.java
> +                    //startPauseBT.setActionCommand("Start");
just a reminder for all of these comments to delete them later to make it more readable

2022-11-21 20:46 UTC, happynasit commented on src/main/java/Need/Timer_countdown_hour.java
> +        timer = new Timer(60 * 1000, new ActionListener() {
Please add java doc to describe the implementation.

2022-11-21 20:49 UTC, MadhavKanna requested changes

2022-11-21 20:49 UTC, MadhavKanna commented on src/main/java/Need/Timer_countdown.java
> +public class Timer_countdown {
Please add JavaDoc for all methods

2022-11-21 20:49 UTC, MadhavKanna commented on src/main/java/Need/Timer_countdown_hour.java
> +public class Timer_countdown_hour {
Please add JavaDoc

2022-11-21 20:49 UTC, MadhavKanna commented on src/main/java/use_cases/SetTimer.java
> +    {
Please remove code that's not in use to avoid code smells (dead code) and to make code readable.

2022-11-21 20:49 UTC, MadhavKanna commented on src/main/java/use_cases/editTimerInputBoundary.java
> +
Please remove dead code(code smell), or implement required code.

2022-11-21 20:49 UTC, MadhavKanna commented on src/test/java/UI/TimerViewTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Please remove dead code(code smell), or implement required code. Thanks!

2022-11-21 22:21 UTC, happynasit commented on src/main/java/Need/Timer_1.java
> +public class Timer_1 {
Please include the description of the class with details about the parameters (@param).

2022-11-21 22:25 UTC, happynasit approved these changes

2022-11-21 22:33 UTC, happynasit submitted a review, later dismissed

2022-11-22 04:24 UTC, m-banthwan commented on src/main/java/Need/Cycle.java
> +
Please add JavaDoc for the methods

2022-11-22 04:25 UTC, m-banthwan commented on src/main/java/Need/Normal_Timer.java
> +public class Normal_Timer {
Please add JavaDoc for the method

2022-11-25 22:32 UTC, happynasit submitted a review, later dismissed

2022-11-25 22:43 UTC, m-banthwan submitted a review, later dismissed

2022-11-25 22:43 UTC, MadhavKanna approved these changes
All files look good, approved for merge!

2022-11-25 23:15 UTC, EmilyDo approved these changes

2022-11-25 23:53 UTC, EmilyDo approved these changes

2022-11-25 23:53 UTC, happynasit approved these changes

2022-11-25 23:53 UTC, MadhavKanna approved these changes
approved!

2022-11-25 23:54 UTC, merged